# Bandit configuration for RLHF Audit Trail security scanning

exclude_dirs:
  - tests
  - venv
  - .venv
  - env
  - .env
  - build
  - dist
  - .git
  - .tox
  - node_modules

# Test IDs to skip with justification
skips:
  - B101  # Use of assert detected (OK in test files)
  - B601  # shell=True usage (needed for deployment scripts)

# Confidence and severity levels
confidence: HIGH
severity: HIGH

# Output format
format: json
output: reports/bandit-report.json

# Additional configuration for AI/ML security
tests:
  - B102  # exec_used
  - B103  # set_bad_file_permissions  
  - B104  # hardcoded_bind_all_interfaces
  - B105  # hardcoded_password_string
  - B106  # hardcoded_password_funcarg
  - B107  # hardcoded_password_default
  - B108  # hardcoded_tmp_directory
  - B110  # try_except_pass
  - B112  # try_except_continue
  - B201  # flask_debug_true
  - B301  # pickle usage (important for ML models)
  - B302  # marshal usage
  - B303  # md5 usage
  - B304  # insecure cipher usage
  - B305  # cipher usage
  - B306  # mktemp usage
  - B307  # eval usage
  - B308  # mark_safe usage
  - B309  # httpsconnection usage
  - B310  # urllib_urlopen
  - B311  # random usage
  - B312  # telnetlib usage
  - B313  # xml usage
  - B314  # xml usage
  - B315  # xml usage
  - B316  # xml usage
  - B317  # xml usage
  - B318  # xml usage
  - B319  # xml usage
  - B320  # xml usage
  - B321  # ftplib usage
  - B322  # input usage
  - B323  # unverified_context
  - B324  # hashlib_new_insecure_functions
  - B325  # tempfile usage
  - B401  # import_telnetlib
  - B402  # import_ftplib
  - B403  # import_pickle (critical for ML)
  - B404  # import_subprocess
  - B405  # import_xml_etree
  - B406  # import_xml_sax
  - B407  # import_xml_expat
  - B408  # import_xml_minidom
  - B409  # import_xml_pulldom
  - B410  # import_lxml
  - B411  # import_xmlrpclib
  - B412  # import_httpoxy
  - B413  # import_pycrypto
  - B501  # request_with_no_cert_validation
  - B502  # ssl_with_bad_version
  - B503  # ssl_with_bad_defaults
  - B504  # ssl_with_no_version
  - B505  # weak_cryptographic_key
  - B506  # yaml_load
  - B507  # ssh_no_host_key_verification
  - B601  # paramiko_calls
  - B602  # subprocess_popen_with_shell_equals_true
  - B603  # subprocess_without_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B605  # start_process_with_a_shell
  - B606  # start_process_with_no_shell
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions
  - B609  # linux_commands_wildcard_injection
  - B610  # django_extra_used
  - B611  # django_rawsql_used
  - B701  # jinja2_autoescape_false
  - B702  # use_of_mako_templates
  - B703  # django_mark_safe