# Loki configuration for RLHF Audit Trail log aggregation
# Optimized for compliance logging and audit trail requirements

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Retention configuration for compliance
limits_config:
  # Enforce retention for compliance (7 years for EU AI Act)
  retention_period: 2557d  # 7 years
  
  # Rate limiting
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_global_streams_per_user: 10000
  max_query_length: 721h  # 30 days
  max_query_parallelism: 32
  max_streams_per_user: 0
  max_line_size: 256000
  
  # Compliance-specific settings
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 1 week
  creation_grace_period: 10m

# Compactor for log retention management
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Analytics for compliance reporting
analytics:
  reporting_enabled: false

# Table manager (deprecated but included for compatibility)
table_manager:
  retention_deletes_enabled: true
  retention_period: 2557d  # 7 years for compliance

# Frontend configuration
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true
  log_queries_longer_than: 5s

frontend_worker:
  match_max_concurrent: true

# Distributor configuration
distributor:
  ring:
    kvstore:
      store: inmemory

# Ingester configuration
ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

# Querier configuration
querier:
  query_timeout: 1m
  tail_max_duration: 1h

# Query frontend configuration
query_scheduler:
  max_outstanding_requests_per_tenant: 256

# Memberlist configuration
memberlist:
  join_members: []