name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you've completed these steps
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true
        - label: I've checked the roadmap and documentation
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - RLHF Algorithm Enhancement
        - Audit Trail Capabilities
        - Privacy/Security Features
        - Compliance/Regulatory
        - API/Integration
        - Dashboard/UI
        - Performance/Optimization
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions you've considered...

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: |
        Provide a concrete example of how you would use this feature:
        - Context: [what you're trying to achieve]
        - Workflow: [step-by-step usage]
        - Expected outcome: [what result you expect]
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Any specific requirements or constraints?
      placeholder: |
        - Compliance requirements (EU AI Act, NIST, etc.)
        - Performance requirements
        - Integration requirements
        - Security considerations

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help with implementation?
      options:
        - label: I can help with design/planning
        - label: I can contribute code
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else you'd like to add?
      placeholder: Links, references, mockups, etc...