apiVersion: v1
kind: Namespace
metadata:
  name: rlhf-audit-trail
  labels:
    app.kubernetes.io/name: rlhf-audit-trail
    app.kubernetes.io/part-of: rlhf-audit-trail
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    field.cattle.io/description: "RLHF Audit Trail production environment"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rlhf-audit-trail-quota
  namespace: rlhf-audit-trail
spec:
  hard:
    # Compute resources
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    
    # Storage resources
    requests.storage: "100Gi"
    persistentvolumeclaims: "10"
    
    # Object counts
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
    
    # Networking
    services.nodeports: "0"
    services.loadbalancers: "3"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rlhf-audit-trail-limits
  namespace: rlhf-audit-trail
spec:
  limits:
  # Container limits
  - default:
      cpu: "1000m"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4000m"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
  
  # Pod limits  
  - max:
      cpu: "8000m"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Pod
  
  # PVC limits
  - max:
      storage: "50Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim